resources:
  - name: repo
    type: git
    icon: github
    source:
      uri: https://github.com/astestqa/Cypress-2.git
      branch: master

jobs:
  - name: test
    public: true
    plan:
      - get: repo
        trigger: true
      - task: run-cypress-tests
        config:
          platform: linux
          inputs:
            - name: repo
          image_resource:
            type: registry-image
            source:
              repository: cypress/included
          run:
            path: /bin/bash
            dir: repo
            args:
              - -cx
              - |
                npm ci # clean install project
                npm run cy:ci # check package.json > scripts > cy:ci
