# References: 
# - https://github.com/marketplace/actions/cypress-io#end-to-end-testing
# - https://github.com/marketplace/actions/cypress-io#record-test-results-on-cypress-cloud

name: Cypress Tests

on: 
  push:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run cy:ci
